#!/usr/local/bin/python
#coding=utf-8
import os, sys, telnetlib
def zalyshok(sim):
    host = '172.16.0.11'
    tn = telnetlib.Telnet(host)
    tn.write("\n\r")
    tn.read_until('SG login: ',5)
    tn.write("2n\r")
    tn.read_until('Password: ',5)
    tn.write("2n\r")
    out_ok = tn.read_until('OK',5)
    ussd112='at&g' + str(sim) + '=xtd*112#;\r'
    tn.write(ussd112)
    out_sms = tn.read_until('S;',6)
    tn.close()
    if out_sms.find('ZALYSHOK')== -1:
        zal = zalyshok(sim)
    else:
        zal = out_sms[out_sms.find('ZALYSHOK'):-1]
        zal = zal[10:-4]
    return zal

sim = sys.argv[1]
balance = zalyshok(sim)
if int(balance) > 50:
    mess = 'OK - balance ' + balance + ' sms'
    print mess
    sys.exit(0)
elif int(balance) > 20:
    mess = 'WARNING - balance ' + balance + ' sms'
    print mess
    sys.exit(1)
elif int(balance) < 11:
    mess = 'CRITICAL - balance ' + balance + ' sms'
    print mess
    sys.exit(2)
else:
    mess = 'UNKNOWN - balance ' + balance + ' sms'
    print mess
    sys.exit(3)
